"""
Django settings for HRproj project.

Generated by 'django-admin startproject' using Django 4.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ak^vrhhgy3rgmes$4qm50nd_h^dkb71%enp58aqh!e+t184)d%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

EMAIL_USE_TLS = False  
EMAIL_HOST = config('SMTPHOST')  
EMAIL_PORT = config('SMTPPORT')  
# EMAIL_HOST_USER = 'irfan.iit003@gmail.com'  
# EMAIL_HOST_PASSWORD = '*********'  

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'Log',
    'tokens',
    'managebusinessunit',
    'managecompany',
    'ManageCustomer',
    'manageserviceline',
    'ManageLocation',
    'ManageExperienceLevel',
    'ManageDesignation',
    'ManageBand',
    'ManageSubBand',
    'ManageAvgCTC',
    'ManageInsurance',
    'manageroles',
    'ManageIndustry',
    'ManageAdUsers',
    'managestages',
    'jobpost',
    "ManageUserRoles",
    "login",
    'drf_yasg',
    'candidate',
    'pdf',
    'Employementtype',
    'Qualification',
    'document',
    'selectedcandidate',
    'zipfiles',
    'DepartmentInfo',
    'Scheduler',
    'operationalmails'

]

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HRproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HRproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
    #},
    'default': {
        'ENGINE': 'mssql',
        'NAME': config('DBNAME') if config('ENVIRONMENT') == 'Dev' else config('DBNAME_PROD') ,
        'USER': config('USER') if config('ENVIRONMENT') == 'Dev' else config('USER_PROD'),  
        'PASSWORD': config("DBPASSWORD") if config('ENVIRONMENT') == 'Dev' else config('DBPASSWORD_PROD'),
        'HOST': config("HOST") if config('ENVIRONMENT') == 'Dev' else config('HOST_PROD'),
        'OPTIONS': {"driver": config("DriverVersion") if config('ENVIRONMENT') == 'Dev' else config('DriverVersion_PROD'), 
        },
        
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-12s %(levelname)-8s %(message)s'
        },
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        }
    },
    'handlers': {
        'console': {     
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'verbose',
            # 'when': 'M',
            # 'interval':1,
            # 'backupCount': 5,
            # 'filename': r'C:\Users\dkanagala\Desktop\Django\HRproj\logging.log'
            'filename': config("LogFileName")
        }
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['file']
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
   # 'EXCEPTION_HANDLER': "HRproj.urls.api_exception_handler",
}
# REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"]=["rest_framework.permissions.AllowAny"] if config("APPMODE")=="DEBUGGING" else print()
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=0,hours=3,minutes=0),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    # 'SIGNING_KEY': env('SIMPLE_JWT_SIGNING_KEY', default=None) or SECRET_KEY,
    'SIGNING_KEY':  SECRET_KEY,
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'JWT_VERIFY': True
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
ROOT_URL=os.path.join(BASE_DIR,'a')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.static',
            ],
        },
    },
]

APP_URL = config("APP_URL")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
# SEND_EMAIL = config("SEND_EMAIL")
SEND_EMAIL = False if config('ENVIRONMENT') == 'Dev' else config('SEND_EMAIL')

